---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1658370/public_html/beherocompany.com
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp prepos-6.config $DEPLOYPATH
    - /bin/cp prepos.config $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
